name: Build and Deploy to Azure Web App

on:
  push:
    tags: 
      - deploytest/** 

env: 
  AZURE_WEBAPP_NAME: leosjobbland 
  AZURE_WEBAPP_PACKAGE_PATH: './frontend/vite-project/dist'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Java for Spring Boot
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Build Spring Boot Backend
      - name: Build Backend
        working-directory: ./backend
        run: |
          mvn clean package
          ls -lh target/*.jar 


      # Set up Node.js for Frontend
      - name: Set up Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: ./frontend/vite-project/package-lock.json

      # Install and Build Frontend
      - name: Build Frontend
        working-directory: ./frontend/vite-project
        run: |
          npm install
          npm run build
          ls -lh dist/  # Verify build files exist

      - name: 'Deploy to Azure WebApp'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZUREWEBAPPPUBLISH }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}


     
       
     

    

      
